<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>LyfStack.Agent.Windows</RootNamespace>
    <AssemblyName>LyfStack.Agent.Windows</AssemblyName>
    <ApplicationIcon />
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LyfStack.Agent.Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <PackageReference Include="System.Management" Version="10.0.10" />
  </ItemGroup>

</Project>
